# Generated by Django 5.2.3 on 2025-06-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ride",
            name="driver_name",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="ride",
            name="driver_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
